export enum Tipo {
    DOUBLE,
    STRING ,
    CHAR,
    VOID ,
    BOOLEAN,
    INT
}

export enum TipoOperacion{
    SUMA, RESTA, MULTIPLICACION,DIVISION,MENOSUNARIO,
    MAYOR,MENOR,MAYORIGUAL,MENORIGUAL,IGUALIGUAL,DISTINTO,
    OR,AND,NOT,XOR,INCREMENTO,DECREMENTO
}


